config/routes.rb
Rails.application.routes.draw do
  resources :seances

   root 'seances#index'

end

app/models/seance.rb
class Seance < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/seances_controller.rb
class SeancesController < ApplicationController
  before_action :set_seance, only: [:show, :edit, :update, :destroy]

  # GET /seances
  # GET /seances.json
  def index
    @seances = Seance.all
  end

  # GET /seances/1
  # GET /seances/1.json
  def show
  end

  # GET /seances/new
  def new
    @seance = Seance.new
  end

  # GET /seances/1/edit
  def edit
  end

  # POST /seances
  # POST /seances.json
  def create
    @seance = Seance.new(seance_params)

    respond_to do |format|
      if @seance.save
        format.html { redirect_to @seance, notice: 'Seance was successfully created.' }
        format.json { render :show, status: :created, location: @seance }
      else
        format.html { render :new }
        format.json { render json: @seance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seances/1
  # PATCH/PUT /seances/1.json
  def update
    respond_to do |format|
      if @seance.update(seance_params)
        format.html { redirect_to @seance, notice: 'Seance was successfully updated.' }
        format.json { render :show, status: :ok, location: @seance }
      else
        format.html { render :edit }
        format.json { render json: @seance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seances/1
  # DELETE /seances/1.json
  def destroy
    @seance.destroy
    respond_to do |format|
      format.html { redirect_to seances_url, notice: 'Seance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seance
      @seance = Seance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seance_params
      params.require(:seance).permit(:titre, :contenu, :url_video, :url_question)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/seances_helper.rb
module SeancesHelper

	def embed_yt(youtube_url)
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  	end

end

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Informatique App", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Acceuil</a></li>
            <li><a href="#about">Niveau</a></li>
            <li><a href="#contact">Aide</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aideinformatique</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/seances/_form.html.erb
<div class="col-md-6 col-md-offset-3">
<%= form_for(@seance) do |f| %>
  <% if @seance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seance.errors.count, "error") %> prohibited this seance from being saved:</h2>

      <ul>
      <% @seance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %><br>
    <%= f.text_field :titre %>
  </div>
  <div class="field">
    <%= f.label :contenu %><br>
    <%= f.text_area :contenu, id: "wysiwyg" %>
  </div>
  <div class="field">
    <%= f.label :url_video %><br>
    <%= f.text_field :url_video %>
  </div>
  <div class="field">
    <%= f.label :url_question %><br>
    <%= f.text_field :url_question %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
<script>
  $('#wysiwyg').froalaEditor({
    inlineMode: false,
    minHeight: '200px',
    buttons: ['bold', 'italic', 'inderline', 'formatBlock', 'align', 'insertUnorderedList', 'insertOrderList', 'outdent', 'indent', 'createLink', 'html'],
  })
</script>

app/views/seances/edit.html.erb
<h1>Editing Seance</h1>

<%= render 'form' %>

<%= link_to 'Show', @seance %> |
<%= link_to 'Back', seances_path %>

app/views/seances/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Apprendre l'informatique </title>
  </head>

  <body>
<p id="notice"><%= notice %></p>
  <div class="container">
  <div class="jumbotron">
      <div class="container">
        <h1>Bienvenu!, élève !</h1>
        <p>ce site à pour l'objectif de vous aider à bien comprendre le cours, faire des TPs, et répondre à des éxercices.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Apprendre Plus &raquo;</a></p>
      </div>
    </div>
    </div>
 


<div class="container">
<h1>Liste des scéances</h1>
<div class="row">
<% @seances.each do |seance| %>

  <div class="box_index">
      <div class="panel panel-success">
        <div class="panel panel-heading">
          <%= seance.titre %>
        </div>
        <div class="panel panel-body">
         <%= truncate(seance.contenu, length: 20) %>
        </div>
       <p><%= link_to "Acceder", seance, class: "btn btn-default" %></p> 

      </div>
      
  </div>

  <% end %>
</div>
</div>
  </body>
</html>

app/views/seances/new.html.erb
<div class="col-md-6 col-md-offset-3">
<h1>New Seance</h1>

<%= render 'form' %>

<%= link_to 'Back', seances_path, class: "btn btn-default" %>	
</div>

app/views/seances/show.html.erb
<p id="notice"><%= notice %></p>
<div class="box">
<div class="titre">
	<h1><%= @seance.titre %></h1>
</div>
<h2> I- Regarder la video</h2>
<div class="embed-container">
	<%= embed_yt(@seance.url_video) %>
</div>
 <div class="contenu">
<h2> II- Lire attentivement</h2>
	<%= simple_format(@seance.contenu) %>
 </div>

 <div class="question">
  <h2>repondre aux questions suivantes</h2>
 	<%= link_to "Exercice", "#{@seance.url_question}", class: "btn btn-default", target: "_blank" %>
 </div>
  


</div>	